FROM node:12 as build-stage
WORKDIR /212digital
COPY /template .
RUN yarn cache clean
RUN yarn install
RUN yarn build

FROM nginx as production-stage
RUN mkdir -p /app/212digital
COPY --from=build-stage /212digital/build /app/212digital
COPY /template/nginx.conf /etc/nginx/nginx.conf